package at.fhooe.mcm.lri.smdm.server;

import com.ejt.vaadin.loginform.LoginForm;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;

public class testLogin extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private LoginForm loginForm_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public testLogin() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// loginForm_1
		loginForm_1 = new LoginForm() {
			
			@Override
			protected void login(String userName, String password) {
				System.err.println(
		                "Logged in with user name " + userName +
		                " and password of length " + password.length()
		            );
			}
			
			@Override
			protected Component createContent(TextField userNameField,
					PasswordField passwordField, Button loginButton) {
				HorizontalLayout layout = new HorizontalLayout();
	            layout.setSpacing(true);
	            layout.setMargin(true);

	            layout.addComponent(userNameField);
	            layout.addComponent(passwordField);
	            layout.addComponent(loginButton);
	            layout.setComponentAlignment(loginButton, Alignment.BOTTOM_LEFT);
	            return layout;
			}
		};
		loginForm_1.setStyleName("v-loginform");
		loginForm_1.setImmediate(false);
		loginForm_1.setWidth("-1px");
		loginForm_1.setHeight("-1px");
		mainLayout.addComponent(loginForm_1, "top:110.0px;left:140.0px;");
		
		return mainLayout;
	}

}
